name: svesely
favicon: null
layout_spectrum: 0.8377582621760666
typography_spectrum: 0.3850068363826722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23820822383277118
  lightness: 0.8265171784441918
  saturation: 0.8392095640301704
  rhythmicContrast: 0.9846854254137725
purpose: []
